# selección condicional de un array: 
## basado en un filtro con una condición y mascara

In [2]:
import numpy as np

# como puede fijar una semilla para el random siempre sea el mismo cuando ejecute el código
# seed su valor sea un numero fijo 
arreglo = np.random.seed(123)

# permite crear números al azar entre un rango
arreglo = np.random.randint(0, 10, 20)

In [6]:
# filtres valores mayores o iguales a 0

mascara_numeros_grandes = arreglo >= 0
# crea un valor booleano en que verifica que la entrada cumpla la condicion o no
mascara_numeros_grandes

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [7]:
datos_filtrados = arreglo[mascara_numeros_grandes]
datos_filtrados

array([1, 9, 2, 7, 4, 5, 5, 3, 5, 1, 4, 8, 7, 5, 3, 9, 6, 8, 9, 3])

In [9]:
# filtrar los elementos pares del array

mascara_numeros_grandes = arreglo % 2 == 0

mascara_numeros_grandes

array([False, False,  True, False,  True, False, False, False, False,
       False,  True,  True, False, False, False, False,  True,  True,
       False, False])

In [ ]:
# Operaciones matematicas con array. tiene que coincidir las dimensiones 

In [ ]:
# suma de dos arrays de la misma dimesion
arreglo_1 = np.random.randint(0, 10, 5)
arreglo_2 = np.random.randint(0, 10, 5)

In [ ]:
#operaciones
arreglo_1 - arreglo_2
arreglo_1 + arreglo_2
arreglo_1 / arreglo_2
arreglo_1 * arreglo_2
arreglo_1 ** 2

# calcula la exponencial a un nuevo arreglo
np.exp(arreglo_1)

# producto escalar
arreglo_1.dot(arreglo_2)
# otra forma
np.sum(arreglo_1 * arreglo_2)

#necesito hacer el arreglo vectorial entre dos productos

#radio del volumen de una esfera

# Pandas

In [17]:
# es una libreria de datos similar a numpy
import pandas as pd

In [23]:
# crear un dataframe de estudiantes de matematica a partir de un diccionario

estudiantes_ds = {
    "nombre": [
        "Claudio Bahamonde",
        "Felipe Abarzúa",
        "Diego Rodriguez",
        "Javier Pizarro",
        "Smilling Battaglini",
        "Pamela Labbé",
        "Marilina Fuentes",
    ],
    "edad": [25, 26, 27, 28, 29, 30, 31],
    "nota": [1, 2, 3, 4, 5, 6, 7],
}

estudiantes_ds_df = pd.DataFrame(estudiantes_ds)

In [24]:
#key valores columnas, values los valores

# visualizar
estudiantes_ds_df

nombre  edad  nota
0    Claudio Bahamonde    25     1
1       Felipe Abarzúa    26     2
2      Diego Rodriguez    27     3
3       Javier Pizarro    28     4
4  Smilling Battaglini    29     5
5         Pamela Labbé    30     6
6     Marilina Fuentes    31     7

In [26]:
# muestra las primeras 4 filas del dataframe, coloco 2 muestra solo dos
estudiantes_ds_df.head(2)

nombre  edad  nota
0  Claudio Bahamonde    25     1
1     Felipe Abarzúa    26     2

In [27]:
# tipos de las columnas
estudiantes_ds_df.dtypes

nombre    object
edad       int64
nota       int64
dtype: object

In [28]:
# hacer una estadistica descriptiva
estudiantes_ds_df.describe()

# en la practica dan los formatos usualmente en .csv en pandas se pueden acceder a esos datos

edad      nota
count   7.000000  7.000000
mean   28.000000  4.000000
std     2.160247  2.160247
min    25.000000  1.000000
25%    26.500000  2.500000
50%    28.000000  4.000000
75%    29.500000  5.500000
max    31.000000  7.000000

In [ ]:
 # como usar pandas con datos externos